@url_dev=http://localhost:3052/v1/api


### SignUp
POST {{url_dev}}/shop/sign-up
Content-Type: application/json

{
  "name": "Shop TipJS",
  "email": "shoptipjs@gmail.com",
  "password": "#Duy2201"
}