@url_dev=http://localhost:3052/v1/api


### SignUp
POST {{url_dev}}/shop/sign-up
Content-Type: application/json
x-api-key: edcf7bb57ac110525e603f8d85d24fad0dbcd67b68536aabad113982fe1060ba6a98ced744edb5bb40fc15aefde61a5c3b8eee46b5daf796fe1896befb0133ce

{
  "name": "VAM Shop",
  "email": "vamshop@gmail.com",
  "password": "#Duy2201"
}